version: '3'

services:
  backend:
    build: ./backend
    container_name: backend
    restart: always
    tty: true
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - network
    volumes:
     - ./backend/backsrc/vol:/usr/src/app/

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    volumes:
      - node_modules_front:/usr/src/app/node_modules
    ports:
      - 8080:8080
    command: npm run serve
    networks:
      - network
    depends_on:
      - backend

  postgre:
    build: ./postgreSQL/
    container_name: postgre
    restart: always
    env_file:
      - .env
    tty: true
    ports:
      - "5432:5432"
    networks:
      - network

networks:
  network:
    driver: bridge
volumes:
  node_modules_front:
  